var gulp = require('gulp');
var sass = require('gulp-sass');
var header = require('gulp-header');

var isProduction = process.env.TRAVIS_BRANCH === 'master' && process.env.TRAVIS_PULL_REQUEST === 'false';
var redeploy = null;

const CSS_HEADER = `/*
  * DO NOT EDIT THIS FILE
  * Your changes will be overwritten by the build process!
  * Go to https://github.com/VolunteerLiveteam/VLT-Reddit-Stylesheet, or ask someone in #technical to help.
  * Last updated at: ${new Date().toLocaleString()}
*/
`;

gulp.task('sass', function() {
  return gulp.src('./sass/index.scss')
    .pipe(sass({outputStyle: 'compressed'}).on('error', sass.logError))
    .pipe(header(CSS_HEADER))
    .pipe(gulp.dest('./build'));
});

gulp.task('reddit', function() {
  redeploy = require('redeploy')({
    subreddit: isProduction ? 'VolunteerLiveTeam' : 'VolunteerTestTeam'
  });
})

gulp.task('deploy', ['deploy-images', 'deploy-css']);

gulp.task('deploy-css', ['reddit', 'sass'], function() {
  return gulp.src('./build/*.css')
    .pipe(redeploy.css());
});

gulp.task('deploy-images', ['reddit'], function() {
  return gulp.src('img/*.png')
    .pipe(redeploy.images());
});